name: setup_dotfiles

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: install git
        run: apt-get update -y && apt-get install -y git
      - uses: actions/checkout@v4
      - name: setup
        run: bash setup.sh
        env:
          DOTFILES_ROOT: ${{ github.workspace }}
          ADDONS: "false"
          DEBIAN_FRONTEND: noninteractive
      - name: test
        run: bats tests/

  ci-centos:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
      - name: install git
        run: dnf install -y git
      - uses: actions/checkout@v4
      - name: setup
        run: bash setup.sh
        env:
          DOTFILES_ROOT: ${{ github.workspace }}
          ADDONS: "false"
      - name: test
        run: bats tests/
