name: setup_dotfiles
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
          # os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: sudo bash setup.sh
